//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : ProjetoSB
//  @ File Name : CodigoOut.h
//  @ Date : 09/01/2013
//  @ Author : Willian
//
//


#ifndef _CODIGOOUT_H
#define _CODIGOOUT_H

#include <string>
#include <list>
#include "CodigoIn.h"
#include <fstream>

using namespace std;
class CodigoOut {
public:
	CodigoOut(){
		this->abreArquivo();

	};
	CodigoOut(string url){
		this->url = url;
		this->abreArquivo();
	};
	void novaLinha(string linha);
	string pegaLinha(int numLinha);
	void setLinha(int numLinha,string novaLinha);
	void escreveSaida(void);
	void mostraSaida ();
private:
	CodigoIn CodIn;
	string url;
	list<string> codigo;
	fstream Saida;

	void abreArquivo();
};


#endif  //_CODIGOOUT_H
