//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : ProjetoSB
//  @ File Name : CodigoIn.h
//  @ Date : 09/01/2013
//  @ Author : Willian
//
//

#ifndef _CODIGOIN_H
#define _CODIGOIN_H

#include <iostream>
#include <fstream>
#include <string>

using namespace std;

class CodigoIn {
public:
	string pegaLinha();
	CodigoIn(){
		this->abreArquivo();
	};

private:
	string url;
	fstream Entrada;
	void abreArquivo();

};

#endif  //_CODIGOIN_H
