//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : ProjetoSB
//  @ File Name : CodigoOut.cpp
//  @ Date : 09/01/2013
//  @ Author : Willian
//
//


#include "CodigoOut.h"

void CodigoOut::novaLinha(string linha) {

}

string CodigoOut::pegaLinha(int numLinha) {

}

void CodigoOut::setLinha(int numLinha, string novaLinha) {

}

void CodigoOut::escreveSaida() {

}

