//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : ProjetoSB
//  @ File Name : CodigoIn.cpp
//  @ Date : 09/01/2013
//  @ Author : Willian
//
//


#include "CodigoIn.h"

string CodigoIn::pegaLinha() {

}

