//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : ProjetoSB
//  @ File Name : CodigoOut.cpp
//  @ Date : 09/01/2013
//  @ Author : Willian
//
//

#include "CodigoOut.h"

void CodigoOut::novaLinha(string linha) {
	codigo.push_front(linha);
}

void CodigoOut::escreveSaida() {
	if (Saida.eof()) {
		Saida.close();
	}

	while(!codigo.empty()){

		Saida << codigo.back() << endl;
		codigo.pop_back();
	}
}

void CodigoOut::mostraSaida () {
	list<string>::const_iterator i;
	cout << "Lista de instruções decodificadas: ";
	for( i = codigo.begin(); i != codigo.end(); ++i)
		cout << *i << " - " << *i << endl;
	cout << endl;
}

void CodigoOut::abreArquivo(){

	Saida.open("saida.s", ios::out);
	if(!Saida.is_open())
		cout << "Problema ao abrir o arquivo de saida!" << endl;
	else cout << "Arquivo aberto com sucesso!" << endl;


}

