//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : ProjetoSB
//  @ File Name : CodigoOut.h
//  @ Date : 09/01/2013
//  @ Author : Willian
//
//


#ifndef _CODIGOOUT_H
#define _CODIGOOUT_H

class CodigoOut {
public:
	string pegaLinha(int numLinha);
	void setLinha(int numLinha,string novaLinha);
	void escreveSaida();
private:
	string url;
	List<string> codigo;
};

#endif  //_CODIGOOUT_H
