//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : ProjetoSB
//  @ File Name : CodigoIn.h
//  @ Date : 09/01/2013
//  @ Author : Willian
//
//

#ifndef _CODIGOIN_H
#define _CODIGOIN_H

#include <string>

using namespace std;

class CodigoIn {
public:
	string pegaLinha();
private:
	string url;
};

#endif  //_CODIGOIN_H
