//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : ProjetoSB
//  @ File Name : ItemRegistrador.h
//  @ Date : 09/01/2013
//  @ Author : Willian
//
//


#ifndef _ITEMREGISTRADOR_H
#define _ITEMREGISTRADOR_H

#include <string>

using namespace std;


struct ItemRegistrador {
	string nome;
	int codigo;
};

#endif  //_ITEMREGISTRADOR_H
