//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : ProjetoSB
//  @ File Name : ItemOperacao.h
//  @ Date : 09/01/2013
//  @ Author : Willian
//
//


#ifndef _ITEMOPERACAO_H
#define _ITEMOPERACAO_H

#include "TipoOperacao.h"

#include <string>

using namespace std;

struct ItemOperacao {
	string nome;
	TipoOperacao tipo;
	string opcode;
	string funct;
	string fmt;
	string endereco;
	string rs;
	string rt;
	string rd;
};

#endif  //_ITEMOPERACAO_H
