//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : ProjetoSB
//  @ File Name : ItemLabel.h
//  @ Date : 09/01/2013
//  @ Author : Willian
//
//


#ifndef _ITEMLABEL_H
#define _ITEMLABEL_H


struct ItemLabel {
	string label;
	string endereco;
};

#endif  //_ITEMLABEL_H
