//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : ProjetoSB
//  @ File Name : Montador.h
//  @ Date : 09/01/2013
//  @ Author : Willian
//
//


#ifndef _MONTADOR_H
#define _MONTADOR_H

#include "CodigoIn.h"
#include "CodigoOut.h"
#include "ItemLabel.h"

#include <string>
#include <list>

using namespace std;

class Montador {
public:
	Montador(int CodigoIn, int CodigoOut);
	void monta();
private:
	CodigoIn codigoIn;
	CodigoOut codigoOut;
	list<ItemLabel> listaLabels;
	list<ItemLabel> listaDependencias;
	void primeiraPassagem();
	void segundaPassagem();
	list<string> separaTokens(string linha);
	string validaTokens(list<string> listaTokens);
};

#endif  //_MONTADOR_H
