//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : ProjetoSB
//  @ File Name : Operacoes.h
//  @ Date : 09/01/2013
//  @ Author : Willian
//
//


#ifndef _OPERACOES_H
#define _OPERACOES_H

#include "ItemOperacao.h"

#include <string>

using namespace std;

static const struct ItemOperacao add = {"Add", R, 0};
static const struct ItemOperacao sub = {"Sub", R, 0};

ItemOperacao encontraOperacao(string nomeOperacao);

#endif  //_OPERACOES_H
