//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : ProjetoSB
//  @ File Name : Registradores.h
//  @ Date : 09/01/2013
//  @ Author : Willian
//
//


#ifndef _REGISTRADORES_H
#define _REGISTRADORES_H

#include "ItemRegistrador.h"

static const struct ItemRegistrador s0 = {"$s0", 0};
static const struct ItemRegistrador s1 = {"$s1", 0};

#endif  //_REGISTRADORES_H
