//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : ProjetoSB
//  @ File Name : Registradores.h
//  @ Date : 09/01/2013
//  @ Author : Willian
//
//


#ifndef _REGISTRADORES_H
#define _REGISTRADORES_H


class Registradores {
public:
	const static ItemRegistrador s0 = {"$s0", 0};
	const static ItemRegistrador s1 = {"$s1", 0};
};

#endif  //_REGISTRADORES_H
