//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : ProjetoSB
//  @ File Name : TipoOperacao.h
//  @ Date : 09/01/2013
//  @ Author : Willian
//
//


#ifndef _TIPOOPERACAO_H
#define _TIPOOPERACAO_H

enum TipoOperacao {
	R,
	FR,
	NULLOP,
//	I,
	J,
//	LABEL
};

#endif  //_TIPOOPERACAO_H
